
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xa1Lw+\xbf1\x16y\x9f\x189\xf0Q#\xf0k'
    
_lr_action_items = {'AND':([2,3,4,9,10,18,19,20,21,22,23,24,25,26,27,28,29,],[-13,-14,11,-12,-7,-8,-6,11,-3,-1,11,-2,-10,11,-9,-11,-15,]),'EVENTUALLY':([0,1,5,6,7,8,11,12,13,14,15,16,17,],[1,1,1,1,1,1,1,1,1,1,1,1,1,]),'FALSE':([0,1,5,6,7,8,11,12,13,14,15,16,17,],[2,2,2,2,2,2,2,2,2,2,2,2,2,]),'UNTIL':([2,3,4,9,10,18,19,20,21,22,23,24,25,26,27,28,29,],[-13,-14,16,-12,-7,-8,-6,16,-3,16,16,16,-10,16,-9,-11,-15,]),'EQUALS':([2,3,4,9,10,18,19,20,21,22,23,24,25,26,27,28,29,],[-13,-14,12,-12,-7,-8,-6,12,-3,-1,-5,-2,-10,-4,-9,-11,-15,]),'NEXT':([0,1,5,6,7,8,11,12,13,14,15,16,17,],[5,5,5,5,5,5,5,5,5,5,5,5,5,]),'GLOBALLY':([0,1,5,6,7,8,11,12,13,14,15,16,17,],[6,6,6,6,6,6,6,6,6,6,6,6,6,]),'RELEASE':([2,3,4,9,10,18,19,20,21,22,23,24,25,26,27,28,29,],[-13,-14,14,-12,-7,-8,-6,14,-3,14,14,14,-10,14,-9,-11,-15,]),'LITERAL':([0,1,5,6,7,8,11,12,13,14,15,16,17,],[3,3,3,3,3,3,3,3,3,3,3,3,3,]),'LPAREN':([0,1,5,6,7,8,11,12,13,14,15,16,17,],[7,7,7,7,7,7,7,7,7,7,7,7,7,]),'NOT':([0,1,5,6,7,8,11,12,13,14,15,16,17,],[8,8,8,8,8,8,8,8,8,8,8,8,8,]),'RPAREN':([2,3,9,10,18,19,20,21,22,23,24,25,26,27,28,29,],[-13,-14,-12,-7,-8,-6,29,-3,-1,-5,-2,-10,-4,-9,-11,-15,]),'IMPLICATION':([2,3,4,9,10,18,19,20,21,22,23,24,25,26,27,28,29,],[-13,-14,15,-12,-7,-8,-6,15,-3,-1,-5,-2,-10,-4,-9,-11,-15,]),'WEAK_UNTIL':([2,3,4,9,10,18,19,20,21,22,23,24,25,26,27,28,29,],[-13,-14,17,-12,-7,-8,-6,17,-3,17,17,17,-10,17,-9,-11,-15,]),'TRUE':([0,1,5,6,7,8,11,12,13,14,15,16,17,],[9,9,9,9,9,9,9,9,9,9,9,9,9,]),'OR':([2,3,4,9,10,18,19,20,21,22,23,24,25,26,27,28,29,],[-13,-14,13,-12,-7,-8,-6,13,-3,-1,13,-2,-10,13,-9,-11,-15,]),'$end':([2,3,4,9,10,18,19,21,22,23,24,25,26,27,28,29,],[-13,-14,0,-12,-7,-8,-6,-3,-1,-5,-2,-10,-4,-9,-11,-15,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,1,5,6,7,8,11,12,13,14,15,16,17,],[4,10,18,19,20,21,22,23,24,25,26,27,28,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr AND expr','expr',3,'p_and','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',55),
  ('expr -> expr OR expr','expr',3,'p_or','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',64),
  ('expr -> NOT expr','expr',2,'p_not','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',68),
  ('expr -> expr IMPLICATION expr','expr',3,'p_implication','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',72),
  ('expr -> expr EQUALS expr','expr',3,'p_equals','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',76),
  ('expr -> GLOBALLY expr','expr',2,'p_globally','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',80),
  ('expr -> EVENTUALLY expr','expr',2,'p_eventually','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',84),
  ('expr -> NEXT expr','expr',2,'p_next','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',88),
  ('expr -> expr UNTIL expr','expr',3,'p_until','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',92),
  ('expr -> expr RELEASE expr','expr',3,'p_release','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',96),
  ('expr -> expr WEAK_UNTIL expr','expr',3,'p_weak_until','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',100),
  ('expr -> TRUE','expr',1,'p_true','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',104),
  ('expr -> FALSE','expr',1,'p_false','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',108),
  ('expr -> LITERAL','expr',1,'p_literal','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',112),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_parenthesis','/Users/antonio/Dropbox/workspace/cool/cool/parser/parser.py',117),
]
